package com.example.mapper;

import com.example.pojo.EmpGenerated;
import com.example.pojo.EmpGeneratedExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EmpGeneratedMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_emp
     *
     * @mbggenerated Sun Mar 29 22:14:20 CST 2026
     */
    int countByExample(EmpGeneratedExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_emp
     *
     * @mbggenerated Sun Mar 29 22:14:20 CST 2026
     */
    int deleteByExample(EmpGeneratedExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_emp
     *
     * @mbggenerated Sun Mar 29 22:14:20 CST 2026
     */
    int deleteByPrimaryKey(Integer empId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_emp
     *
     * @mbggenerated Sun Mar 29 22:14:20 CST 2026
     */
    int insert(EmpGenerated record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_emp
     *
     * @mbggenerated Sun Mar 29 22:14:20 CST 2026
     */
    int insertSelective(EmpGenerated record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_emp
     *
     * @mbggenerated Sun Mar 29 22:14:20 CST 2026
     */
    List<EmpGenerated> selectByExample(EmpGeneratedExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_emp
     *
     * @mbggenerated Sun Mar 29 22:14:20 CST 2026
     */
    EmpGenerated selectByPrimaryKey(Integer empId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_emp
     *
     * @mbggenerated Sun Mar 29 22:14:20 CST 2026
     */
    int updateByExampleSelective(@Param("record") EmpGenerated record, @Param("example") EmpGeneratedExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_emp
     *
     * @mbggenerated Sun Mar 29 22:14:20 CST 2026
     */
    int updateByExample(@Param("record") EmpGenerated record, @Param("example") EmpGeneratedExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_emp
     *
     * @mbggenerated Sun Mar 29 22:14:20 CST 2026
     */
    int updateByPrimaryKeySelective(EmpGenerated record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_emp
     *
     * @mbggenerated Sun Mar 29 22:14:20 CST 2026
     */
    int updateByPrimaryKey(EmpGenerated record);
}